// 'use client';

// export const translations = {
//   English: {
//     settings: 'Settings',
//     allSystemSettings: 'All System Settings',
//     appearance: 'Appearance',
//     customizeTheme: 'Customize how your theme looks on your device',
//     language: 'Language',
//     selectLanguage: 'Select your language',
//     twoFactor: 'Two-factor Authentication',
//     twoFactorDesc: 'Keep your account secure by enabling 2FA via mail',
//     mobilePush: 'Mobile Push Notifications',
//     mobilePushDesc: 'Receive push notification',
//     desktopNotification: 'Desktop Notification',
//     desktopNotificationDesc: 'Receive push notification in desktop',
//     emailNotifications: 'Email Notifications',
//     emailNotificationsDesc: 'Receive email notification',
//     notifications: 'Notifications',
//     newSettings: 'New Settings Available',
//     viewAll: 'View All Notifications',
//     searchPlaceholder: 'Search',

//     // Attendance Page
//     attendance: 'Attendance',
//     allEmployeeAttendance: 'All employee attendance records',
//     designation: 'Designation',
//     employeeName: 'Employee Name',
//     checkInTime: 'Check-In Time',
//     type: 'Type',
//     status: 'Status',
//     showing: 'Showing',
//     records: 'records',
//     search: 'Search',

//     // Candidate List Page
//     candidates: 'Candidates',
//     showAllCandidates: 'Show All Candidates',
//     candidateName: 'Candidate Name',
//     appliedFor: 'Applied For',
//     appliedDate: 'Applied Date',
//     emailAddress: 'Email Address',
//     mobileNumber: 'Mobile Number',
//     robertAllen: 'Robert Allen',
//     hrManager: 'HR Manager',
//     'Robert Allen': 'Robert Allen',
//     selected: 'Selected',
//     inprocess: 'In Process',
//     rejected: 'Rejected',

//     // Job Titles and Others
//     'Team Lead - Design': 'Team Lead - Design',
//     'Web Designer': 'Web Designer',
//     'Medical Assistant': 'Medical Assistant',
//     'Marketing Coordinator': 'Marketing Coordinator',
//     'Data Analyst': 'Data Analyst',
//     'Python Developer': 'Python Developer',
//     'UI/UX Design': 'UI/UX Design',
//     'React JS': 'React JS',
//     'React JS Developer': 'React JS Developer',
//     'IOS Developer': 'IOS Developer',
//     'Office': 'Office',
//     'Remote': 'Remote',
//     'HR Manager': 'HR Manager',
//     prev: 'Previous',
//     next: 'Next',
//      onTime: 'On Time',
//     late: 'Late',
//      allDepartments: "All Departments",
//     allDepartmentsInfo: "View and manage all company departments.",
//     members: "members",
//     'Design Department': 'Design Department',
//     'Sales Department': 'Sales Department',
//     'Project Manager Department': 'Project Manager Department',
//     'Marketing Department': 'Marketing Department',
//      'Sale Department': 'Sale Department',
//     addNewEmployee: 'Add New Employee',
//     filter: 'Filter',
//     all: 'All',
//     office: 'Office',
//     remote: 'Remote',
//     permanent: 'Permanent',
//     employeeID: 'Employee ID',
//     action: 'Action',
//     show: 'Showing',
//     of: 'of',
//      holidays: 'Holidays',
//     allHolidays: 'All Holidays lists',
//     addNewHoliday: 'Add New Holiday',
//     date: 'Date',
//     day: 'Day',
//     holidayName: 'Holiday Name',
//     upcoming: 'Upcoming',
//     pastHolidays: 'Past Holidays',
//     cancel: 'Cancel',
//     add: 'Add',
   
//     "New Year's Day": "New Year's Day",
//     'Genocide Against the Tutsi Memorial Day': 'Genocide Against the Tutsi Memorial Day',
//     'Labour Day': 'Labour Day',
//     'Independence Day': 'Independence Day',
//     'Liberation Day': 'Liberation Day',
//     'Assumption Day': 'Assumption Day',
//     'Umuganura Day': 'Umuganura Day',
//     'All Saints Day': 'All Saints Day',
//     'Christmas Day': 'Christmas Day',
//     'Boxing Day': 'Boxing Day',
//      days: {
//       Sunday: 'Sunday',
//       Monday: 'Monday',
//       Tuesday: 'Tuesday',
//       Wednesday: 'Wednesday',
//       Thursday: 'Thursday',
//       Friday: 'Friday',
//       Saturday: 'Saturday',
//     },
//     months: {
//       January: 'January',
//       February: 'February',
//       March: 'March',
//       April: 'April',
//       May: 'May',
//       June: 'June',
//       July: 'July',
//       August: 'August',
//       September: 'September',
//       October: 'October',
//       November: 'November',
//       December: 'December',
//     },
//      jobs: 'Jobs',
//   showAllJobs: 'Show All Jobs',
//     jobTitle: 'Job Title',
//   addNewJob: 'Add New Job',
//   selectDepartment: 'Select Department',
//   selectLocation: 'Select Location',
//   enterJobTitle: 'Enter Job Title',
//   enterSalary: 'Enter Salary (e.g., $3000)',
//   jobTypeLabel: 'Job Type',
//   workTypeLabel: 'Work Type',
//   fullTime: 'Full Time',
//   partTime: 'Part Time',
//     contract: 'Contract',
//   workFromHome: 'Work from Home',
//     jobDescription: 'Job Description',
//     activeJobs: 'Active Jobs',
//     inactiveJobs: 'Inactive Jobs',
//     completedJobs: 'Completed Jobs',
//     jobResponsibilities: 'Job Responsibilities',
//     jobType: 'Job Type',
//     workType: 'Work Type',
//     selectType: 'Select Type',
//     selectWorkType: 'Select Work Type',
   
//     month: 'Month',
//     fillAllFields: 'Please fill in all required fields',
    
//     // Departments
//     design: 'Design',
//     developer: 'Developer',
//     sales: 'Sales',
//     hr: 'HR',
//     marketing: 'Marketing',
//     finance: 'Finance',
    
//     // Job Titles
//     uiUxDesigner: 'UI/UX Designer',
//     srUxResearcher: 'Sr. UX Researcher',
//     bdm: 'BDM',
//     reactJs: 'React JS',
//     hrExecutive: 'Hr Executive',
//     pythonDeveloper: 'Python Developer',
    
   
   

//   },

//   French: {
//     settings: 'Paramètres',
//     allSystemSettings: 'Tous les paramètres du système',
//     appearance: 'Apparence',
//     customizeTheme: 'Personnalisez le thème de votre appareil',
//     language: 'Langue',
//     selectLanguage: 'Sélectionnez votre langue',
//     twoFactor: 'Authentification à deux facteurs',
//     twoFactorDesc: 'Sécurisez votre compte en activant 2FA par e-mail',
//     mobilePush: 'Notifications Push Mobile',
//     mobilePushDesc: 'Recevoir les notifications push',
//     desktopNotification: 'Notifications sur ordinateur',
//     desktopNotificationDesc: 'Recevoir les notifications push sur ordinateur',
//     emailNotifications: 'Notifications par e-mail',
//     emailNotificationsDesc: 'Recevoir les notifications par e-mail',
//     notifications: 'Notifications',
//     newSettings: 'Nouveaux paramètres disponibles',
//     viewAll: 'Voir toutes les notifications',
//     searchPlaceholder: 'Recherche',

   
//     attendance: 'Présence',
//     allEmployeeAttendance: 'Toutes les présences des employés',
//     designation: 'Poste',
//     employeeName: "Nom de l'employé",
//     checkInTime: "Heure d'arrivée",
//     type: 'Type',
//     status: 'Statut',
//     showing: 'Affichage',
//     records: 'enregistrements',
//     search: 'Recherche',

//     // Candidate List Page
//     candidates: 'Candidats',
//     showAllCandidates: 'Afficher tous les candidats',
//     candidateName: 'Nom du candidat',
//     appliedFor: 'Poste demandé',
//     appliedDate: 'Date de candidature',
//     emailAddress: 'Adresse e-mail',
//     mobileNumber: 'Numéro de téléphone',
//     robertAllen: 'Robert Allen',
//     hrManager: 'Responsable RH',
//     selected: 'Sélectionné',
//     inprocess: 'En cours',
//     rejected: 'Rejeté',

//     // Job Titles and Others
//     'Team Lead - Design': 'Chef d\'équipe - Design',
//     'Web Designer': 'Concepteur Web',
//     'Medical Assistant': 'Assistant médical',
//     'Marketing Coordinator': 'Coordinateur marketing',
//     'Data Analyst': 'Analyste de données',
//     'Python Developer': 'Développeur Python',
//     'UI/UX Design': 'Conception UI/UX',
//     'React JS': 'React JS',
//     'React JS Developer': 'Développeur React JS',
//     'IOS Developer': 'Développeur IOS',
//     'Office': 'Bureau',
//     'Remote': 'Télétravail',
//     'HR Manager': 'Responsable RH',
//     prev: 'Précédent',
//     next: 'Suivant',
//     onTime: 'À l\'heure',
//     late: 'En retard',
//     allDepartments: "Tous les départements",
//     allDepartmentsInfo: "Afficher et gérer tous les départements de l'entreprise.",
//     members: "membres",
//     'Design Department': 'Département de conception',
//     'Sales Department': 'Département des ventes',
//     'Project Manager Department': 'Département de gestion de projet',
//     'Marketing Department': 'Département marketing',
//      'Sale Department': 'Département des ventes',
//     addNewEmployee: 'Ajouter un employé',
//     filter: 'Filtrer',
//     all: 'Tous',
//     office: 'Bureau',
//     remote: 'Télétravail',
//     permanent: 'Permanent',
//     employeeID: "ID d'employé",
//     action: 'Action',
//     show: 'Affichage',
//     of: 'de',
//       holidays: 'Jours Fériés',
//     allHolidays: 'Liste de tous les jours fériés',
//     addNewHoliday: 'Ajouter un jour férié',
//     date: 'Date',
//     day: 'Jour',
//     holidayName: 'Nom du jour férié',
//     upcoming: 'À venir',
//     pastHolidays: 'Jours fériés passés',
//     cancel: 'Annuler',
//     add: 'Ajouter',
//     "New Year's Day": "Jour de l'An",
//     'Genocide Against the Tutsi Memorial Day': 'Commémoration du Génocide contre les Tutsis',
//     'Labour Day': 'Fête du Travail',
//     'Independence Day': "Jour de l'Indépendance",
//     'Liberation Day': 'Jour de la Libération',
//     'Assumption Day': "Assomption",
//     'Umuganura Day': "Jour d'Umuganura",
//     'All Saints Day': "Toussaint",
//     'Christmas Day': "Noël",
//     'Boxing Day': "Lendemain de Noël",
//      days: {
//       Sunday: 'Dimanche',
//       Monday: 'Lundi',
//       Tuesday: 'Mardi',
//       Wednesday: 'Mercredi',
//       Thursday: 'Jeudi',
//       Friday: 'Vendredi',
//       Saturday: 'Samedi',
//     },
//     months: {
//       January: 'Janvier',
//       February: 'Février',
//       March: 'Mars',
//       April: 'Avril',
//       May: 'Mai',
//       June: 'Juin',
//       July: 'Juillet',
//       August: 'Août',
//       September: 'Septembre',
//       October: 'Octobre',
//       November: 'Novembre',
//       December: 'Décembre',
//     },
//     jobs: 'Emplois',
//   showAllJobs: 'Afficher tous les emplois',
//     jobTitle: 'Titre du poste',
//   addNewJob: 'Ajouter un nouvel emploi',
//   selectDepartment: 'Sélectionner un département',
//   selectLocation: 'Sélectionner un lieu',
//   enterJobTitle: 'Entrez le titre du poste',
//   enterSalary: 'Entrez le salaire (ex : 3000 $)',
//   jobTypeLabel: 'Type de poste',
//   workTypeLabel: 'Type de travail',
//   fullTime: 'Temps plein',
//   partTime: 'Temps partiel',
//     contract: 'Contrat',
//   workFromHome: 'Travail à domicile',
//     jobDescription: 'Description du poste',
//     jobResponsibilities: 'Responsabilités du poste',
//     activeJobs: 'Emplois actifs',
//     inactiveJobs: 'Emplois inactifs',
//     completedJobs: 'Emplois terminés',
   
//     jobType: 'Type d\'emploi',
//     workType: 'Type de travail',
//     selectType: 'Sélectionner le type',
//     selectWorkType: 'Sélectionner le type de travail',
//     month: 'Mois',
//     fillAllFields: 'Veuillez remplir tous les champs obligatoires',
    
//     // Departments
//     design: 'Design',
//     developer: 'Développeur',
//     sales: 'Ventes',
//     hr: 'RH',
//     marketing: 'Marketing',
//     finance: 'Finance',
    
//     // Job Titles
//     uiUxDesigner: 'Designer UI/UX',
//     srUxResearcher: 'Chercheur UX Senior',
//     bdm: 'Directeur du développement commercial',
//     reactJs: 'React JS',
//     hrExecutive: 'Responsable RH',
//     pythonDeveloper: 'Développeur Python',
    
//     dataAnalyst: 'Analyste de données',
//     projectManager: 'Chef de projet',
//     },

//   Chinese: {
//     settings: '设置',
//     allSystemSettings: '所有系统设置',
//     appearance: '外观',
//     customizeTheme: '自定义主题外观',
//     language: '语言',
//     selectLanguage: '选择你的语言',
//     twoFactor: '双因素认证',
//     twoFactorDesc: '通过电子邮件启用2FA来保护您的帐户',
//     mobilePush: '手机推送通知',
//     mobilePushDesc: '接收推送通知',
//     desktopNotification: '桌面通知',
//     desktopNotificationDesc: '在桌面上接收推送通知',
//     emailNotifications: '电子邮件通知',
//     emailNotificationsDesc: '接收电子邮件通知',
//     notifications: '通知',
//     newSettings: '新设置可用',
//     viewAll: '查看所有通知',
//     searchPlaceholder: '搜索',

//     // Attendance Page
//     attendance: '出勤情况',
//     allEmployeeAttendance: '所有员工的出勤记录',
//     designation: '职位',
//     employeeName: '员工姓名',
//     checkInTime: '签到时间',
//     type: '类型',
//     status: '状态',
//     showing: '显示',
//     records: '记录',
//     search: '搜索',

//     // Candidate List Page
//     candidates: '候选人',
//     showAllCandidates: '显示所有候选人',
//     candidateName: '候选人姓名',
//     appliedFor: '申请职位',
//     appliedDate: '申请日期',
//     emailAddress: '电子邮件地址',
//     mobileNumber: '电话号码',
//     robertAllen: '罗伯特·艾伦',
//     'Marketing Coordinator': '市场协调员',
//     'Data Analyst': '数据分析师',
//     'Python Developer': 'Python 开发人员',
//     'UI/UX Design': 'UI/UX 设计',
//     'React JS': 'React JS',
//     'React JS Developer': 'React JS 开发人员',
//     'IOS Developer': 'IOS 开发人员',
//     'Office': '办公室',
//     'Remote': '远程',
//     'HR Manager': '人力资源经理',
//     prev: '上一页',
//     next: '下一页',
//      onTime: '准时',
//     late: '迟到',
//     allDepartments: "所有部门",
//     allDepartmentsInfo: "查看和管理公司所有部门。",
//     members: "成员",
//     'Design Department': '设计部',
//     'Sales Department': '销售部',
//     'Project Manager Department': '项目经理部',
//     'Marketing Department': '市场部',
//     'Lead UI/UX Designer': '首席 UI/UX 设计师',
//     'Sr UI/UX Designer': '高级 UI/UX 设计师',
//     'UI/UX Designer': 'UI/UX 设计师',
//     'Sr Sales Manager': '高级销售经理',
//     'BDM': '业务发展经理',
//     'BDE': '业务发展执行',
//     'Sales': '销售',
//     'Sr Project Manager': '高级项目经理',
//     'Project Manager': '项目经理',
//     'Sr Marketing Manager': '高级市场经理',
//     'Marketing': '市场',
//     'Sale Department': '销售部门',
//     addNewEmployee: '添加新员工',
//     filter: '筛选',
//     all: '全部',
//     office: '办公室',
//     remote: '远程',
//     permanent: '永久',
//     employeeID: '员工编号',
//     action: '操作',
//     show: '显示',
//     of: '共',
//      holidays: '节假日',
//     allHolidays: '所有节假日列表',
//     addNewHoliday: '添加节假日',
//     date: '日期',
//     day: '星期',
//     holidayName: '节日名称',
//     upcoming: '即将到来',
//     pastHolidays: '过去的节日',
//     cancel: '取消',
//     add: '添加',

//     'Genocide Against the Tutsi Memorial Day': '对图西人种族灭绝纪念日',
//     'Labour Day': '劳动节',
//     'Independence Day': '独立日',
//     'Liberation Day': '解放日',
//     'Assumption Day': '圣母升天日',
//     'Umuganura Day': '丰收节',
//     'All Saints Day': '万圣节',
//     'Christmas Day': '圣诞节',
//     'Boxing Day': '节礼日',
//      days: {
//       Sunday: '星期日',
//       Monday: '星期一',
//       Tuesday: '星期二',
//       Wednesday: '星期三',
//       Thursday: '星期四',
//       Friday: '星期五',
//       Saturday: '星期六',
//     },
//     months: {
//       January: '一月',
//       February: '二月',
//       March: '三月',
//       April: '四月',
//       May: '五月',
//       June: '六月',
//       July: '七月',
//       August: '八月',
//       September: '九月',
//       October: '十月',
//       November: '十一月',
//       December: '十二月',
//     },
//     jobs: '职位',
//   showAllJobs: '显示所有职位',
//   jobTitle: '职位名称',
//   addNewJob: '添加新职位',
//   selectDepartment: '选择部门',
//   selectLocation: '选择地点',
//   enterJobTitle: '输入职位名称',
//   enterSalary: '输入薪资（如 $3000）',
//   jobTypeLabel: '职位类型',
//   workTypeLabel: '工作类型',
//   fullTime: '全职',
//   partTime: '兼职',
//   workFromHome: '在家工作',
//     contract: '合同',
//     activeJobs: '活跃职位',
//     inactiveJobs: '非活跃职位',
//     completedJobs: '已完成职位',
//     jobDescription: '职位描述',
//     jobResponsibilities: '职位职责',
//     jobType: '工作类型',
//     workType: '工作方式',
   
//     selectType: '选择类型',
//     selectWorkType: '选择工作方式',
//     jobTitlePlaceholder: '输入职位标题',
//     salaryPlaceholder: '输入薪资（如 $3000）',
//     jobDescriptionPlaceholder: '输入职位描述',
//     month: '月',
//     fillAllFields: '请填写所有必填字段',
    
//     // Departments
//     design: '设计',
//     developer: '开发',
//     sales: '销售',
//     hr: '人力资源',
//     marketing: '市场营销',
//     finance: '财务',
    
//     // Job Titles
//     uiUxDesigner: 'UI/UX设计师',
//     srUxResearcher: '高级UX研究员',
//     bdm: '业务发展经理',
//     reactJs: 'React JS',
//     hrExecutive: '人力资源主管',
//     pythonDeveloper: 'Python开发工程师',
    
//     projectManager: '项目经理',
//     businessAnalyst: '业务分析师',
//     },
// };
